// Copyright (C) 2023  Braiins Systems s.r.o.
//
// This file is part of Braiins Open-Source Initiative (BOSI).
//
// BOSI is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Please, keep in mind that we may also license BOSI or any part thereof
// under a proprietary license. For more information on the terms and conditions
// of such proprietary license or if you have any other questions, please
// contact us at opensource@braiins.com.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: bos/version.proto

package bos_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ApiVersionService_GetApiVersion_FullMethodName = "/braiins.bos.ApiVersionService/GetApiVersion"
)

// ApiVersionServiceClient is the client API for ApiVersionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiVersionServiceClient interface {
	GetApiVersion(ctx context.Context, in *ApiVersionRequest, opts ...grpc.CallOption) (*ApiVersion, error)
}

type apiVersionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApiVersionServiceClient(cc grpc.ClientConnInterface) ApiVersionServiceClient {
	return &apiVersionServiceClient{cc}
}

func (c *apiVersionServiceClient) GetApiVersion(ctx context.Context, in *ApiVersionRequest, opts ...grpc.CallOption) (*ApiVersion, error) {
	out := new(ApiVersion)
	err := c.cc.Invoke(ctx, ApiVersionService_GetApiVersion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiVersionServiceServer is the server API for ApiVersionService service.
// All implementations must embed UnimplementedApiVersionServiceServer
// for forward compatibility
type ApiVersionServiceServer interface {
	GetApiVersion(context.Context, *ApiVersionRequest) (*ApiVersion, error)
	mustEmbedUnimplementedApiVersionServiceServer()
}

// UnimplementedApiVersionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedApiVersionServiceServer struct {
}

func (UnimplementedApiVersionServiceServer) GetApiVersion(context.Context, *ApiVersionRequest) (*ApiVersion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApiVersion not implemented")
}
func (UnimplementedApiVersionServiceServer) mustEmbedUnimplementedApiVersionServiceServer() {}

// UnsafeApiVersionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiVersionServiceServer will
// result in compilation errors.
type UnsafeApiVersionServiceServer interface {
	mustEmbedUnimplementedApiVersionServiceServer()
}

func RegisterApiVersionServiceServer(s grpc.ServiceRegistrar, srv ApiVersionServiceServer) {
	s.RegisterService(&ApiVersionService_ServiceDesc, srv)
}

func _ApiVersionService_GetApiVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiVersionServiceServer).GetApiVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApiVersionService_GetApiVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiVersionServiceServer).GetApiVersion(ctx, req.(*ApiVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiVersionService_ServiceDesc is the grpc.ServiceDesc for ApiVersionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiVersionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "braiins.bos.ApiVersionService",
	HandlerType: (*ApiVersionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetApiVersion",
			Handler:    _ApiVersionService_GetApiVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bos/version.proto",
}
