// Copyright (C) 2023  Braiins Systems s.r.o.
//
// This file is part of Braiins Open-Source Initiative (BOSI).
//
// BOSI is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Please, keep in mind that we may also license BOSI or any part thereof
// under a proprietary license. For more information on the terms and conditions
// of such proprietary license or if you have any other questions, please
// contact us at opensource@braiins.com.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: bos/v1/common.proto

package bos_proto_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Save action for different operations
type SaveAction int32

const (
	SaveAction_SAVE_ACTION_UNSPECIFIED          SaveAction = 0
	SaveAction_SAVE_ACTION_SAVE                 SaveAction = 1
	SaveAction_SAVE_ACTION_SAVE_AND_APPLY       SaveAction = 2
	SaveAction_SAVE_ACTION_SAVE_AND_FORCE_APPLY SaveAction = 3
)

// Enum value maps for SaveAction.
var (
	SaveAction_name = map[int32]string{
		0: "SAVE_ACTION_UNSPECIFIED",
		1: "SAVE_ACTION_SAVE",
		2: "SAVE_ACTION_SAVE_AND_APPLY",
		3: "SAVE_ACTION_SAVE_AND_FORCE_APPLY",
	}
	SaveAction_value = map[string]int32{
		"SAVE_ACTION_UNSPECIFIED":          0,
		"SAVE_ACTION_SAVE":                 1,
		"SAVE_ACTION_SAVE_AND_APPLY":       2,
		"SAVE_ACTION_SAVE_AND_FORCE_APPLY": 3,
	}
)

func (x SaveAction) Enum() *SaveAction {
	p := new(SaveAction)
	*p = x
	return p
}

func (x SaveAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SaveAction) Descriptor() protoreflect.EnumDescriptor {
	return file_bos_v1_common_proto_enumTypes[0].Descriptor()
}

func (SaveAction) Type() protoreflect.EnumType {
	return &file_bos_v1_common_proto_enumTypes[0]
}

func (x SaveAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SaveAction.Descriptor instead.
func (SaveAction) EnumDescriptor() ([]byte, []int) {
	return file_bos_v1_common_proto_rawDescGZIP(), []int{0}
}

var File_bos_v1_common_proto protoreflect.FileDescriptor

var file_bos_v1_common_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73, 0x2e, 0x62,
	0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2a, 0x85, 0x01, 0x0a, 0x0a, 0x53, 0x61, 0x76, 0x65, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x41, 0x43, 0x54,
	0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x53, 0x41, 0x56, 0x45, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x53, 0x41, 0x56, 0x45, 0x5f,
	0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x41, 0x4e, 0x44, 0x5f,
	0x41, 0x50, 0x50, 0x4c, 0x59, 0x10, 0x02, 0x12, 0x24, 0x0a, 0x20, 0x53, 0x41, 0x56, 0x45, 0x5f,
	0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x53, 0x41, 0x56, 0x45, 0x5f, 0x41, 0x4e, 0x44, 0x5f,
	0x46, 0x4f, 0x52, 0x43, 0x45, 0x5f, 0x41, 0x50, 0x50, 0x4c, 0x59, 0x10, 0x03, 0x42, 0x3d, 0x5a,
	0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x61, 0x69,
	0x69, 0x6e, 0x73, 0x2f, 0x62, 0x6f, 0x73, 0x2d, 0x70, 0x6c, 0x75, 0x73, 0x2d, 0x61, 0x70, 0x69,
	0x2f, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73, 0x2f, 0x62, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x3b,
	0x62, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bos_v1_common_proto_rawDescOnce sync.Once
	file_bos_v1_common_proto_rawDescData = file_bos_v1_common_proto_rawDesc
)

func file_bos_v1_common_proto_rawDescGZIP() []byte {
	file_bos_v1_common_proto_rawDescOnce.Do(func() {
		file_bos_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_bos_v1_common_proto_rawDescData)
	})
	return file_bos_v1_common_proto_rawDescData
}

var file_bos_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bos_v1_common_proto_goTypes = []interface{}{
	(SaveAction)(0), // 0: braiins.bos.v1.SaveAction
}
var file_bos_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bos_v1_common_proto_init() }
func file_bos_v1_common_proto_init() {
	if File_bos_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bos_v1_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bos_v1_common_proto_goTypes,
		DependencyIndexes: file_bos_v1_common_proto_depIdxs,
		EnumInfos:         file_bos_v1_common_proto_enumTypes,
	}.Build()
	File_bos_v1_common_proto = out.File
	file_bos_v1_common_proto_rawDesc = nil
	file_bos_v1_common_proto_goTypes = nil
	file_bos_v1_common_proto_depIdxs = nil
}
