// Copyright (C) 2023  Braiins Systems s.r.o.
//
// This file is part of Braiins Open-Source Initiative (BOSI).
//
// BOSI is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Please, keep in mind that we may also license BOSI or any part thereof
// under a proprietary license. For more information on the terms and conditions
// of such proprietary license or if you have any other questions, please
// contact us at opensource@braiins.com.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: bos/v1/constraints.proto

package bos_proto_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UInt32Constraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default uint32 `protobuf:"varint,1,opt,name=default,proto3" json:"default,omitempty"`
	Min     uint32 `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max     uint32 `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *UInt32Constraints) Reset() {
	*x = UInt32Constraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_constraints_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UInt32Constraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UInt32Constraints) ProtoMessage() {}

func (x *UInt32Constraints) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_constraints_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UInt32Constraints.ProtoReflect.Descriptor instead.
func (*UInt32Constraints) Descriptor() ([]byte, []int) {
	return file_bos_v1_constraints_proto_rawDescGZIP(), []int{0}
}

func (x *UInt32Constraints) GetDefault() uint32 {
	if x != nil {
		return x.Default
	}
	return 0
}

func (x *UInt32Constraints) GetMin() uint32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *UInt32Constraints) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type DoubleConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default float64 `protobuf:"fixed64,1,opt,name=default,proto3" json:"default,omitempty"`
	Min     float64 `protobuf:"fixed64,2,opt,name=min,proto3" json:"min,omitempty"`
	Max     float64 `protobuf:"fixed64,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *DoubleConstraints) Reset() {
	*x = DoubleConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_constraints_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleConstraints) ProtoMessage() {}

func (x *DoubleConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_constraints_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleConstraints.ProtoReflect.Descriptor instead.
func (*DoubleConstraints) Descriptor() ([]byte, []int) {
	return file_bos_v1_constraints_proto_rawDescGZIP(), []int{1}
}

func (x *DoubleConstraints) GetDefault() float64 {
	if x != nil {
		return x.Default
	}
	return 0
}

func (x *DoubleConstraints) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *DoubleConstraints) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type PowerConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default *Power `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Min     *Power `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	Max     *Power `protobuf:"bytes,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *PowerConstraints) Reset() {
	*x = PowerConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_constraints_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PowerConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerConstraints) ProtoMessage() {}

func (x *PowerConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_constraints_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerConstraints.ProtoReflect.Descriptor instead.
func (*PowerConstraints) Descriptor() ([]byte, []int) {
	return file_bos_v1_constraints_proto_rawDescGZIP(), []int{2}
}

func (x *PowerConstraints) GetDefault() *Power {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *PowerConstraints) GetMin() *Power {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *PowerConstraints) GetMax() *Power {
	if x != nil {
		return x.Max
	}
	return nil
}

type HashrateConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default *TeraHashrate `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Min     *TeraHashrate `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	Max     *TeraHashrate `protobuf:"bytes,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *HashrateConstraints) Reset() {
	*x = HashrateConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_constraints_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashrateConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashrateConstraints) ProtoMessage() {}

func (x *HashrateConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_constraints_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashrateConstraints.ProtoReflect.Descriptor instead.
func (*HashrateConstraints) Descriptor() ([]byte, []int) {
	return file_bos_v1_constraints_proto_rawDescGZIP(), []int{3}
}

func (x *HashrateConstraints) GetDefault() *TeraHashrate {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *HashrateConstraints) GetMin() *TeraHashrate {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *HashrateConstraints) GetMax() *TeraHashrate {
	if x != nil {
		return x.Max
	}
	return nil
}

type TemperatureConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default *Temperature `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Min     *Temperature `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	Max     *Temperature `protobuf:"bytes,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *TemperatureConstraints) Reset() {
	*x = TemperatureConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_constraints_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TemperatureConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureConstraints) ProtoMessage() {}

func (x *TemperatureConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_constraints_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureConstraints.ProtoReflect.Descriptor instead.
func (*TemperatureConstraints) Descriptor() ([]byte, []int) {
	return file_bos_v1_constraints_proto_rawDescGZIP(), []int{4}
}

func (x *TemperatureConstraints) GetDefault() *Temperature {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *TemperatureConstraints) GetMin() *Temperature {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *TemperatureConstraints) GetMax() *Temperature {
	if x != nil {
		return x.Max
	}
	return nil
}

type BooleanConstraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default bool `protobuf:"varint,1,opt,name=default,proto3" json:"default,omitempty"`
}

func (x *BooleanConstraint) Reset() {
	*x = BooleanConstraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_constraints_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BooleanConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanConstraint) ProtoMessage() {}

func (x *BooleanConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_constraints_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanConstraint.ProtoReflect.Descriptor instead.
func (*BooleanConstraint) Descriptor() ([]byte, []int) {
	return file_bos_v1_constraints_proto_rawDescGZIP(), []int{5}
}

func (x *BooleanConstraint) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

type DurationConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default *Hours `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Min     *Hours `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	Max     *Hours `protobuf:"bytes,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *DurationConstraints) Reset() {
	*x = DurationConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_constraints_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DurationConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurationConstraints) ProtoMessage() {}

func (x *DurationConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_constraints_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DurationConstraints.ProtoReflect.Descriptor instead.
func (*DurationConstraints) Descriptor() ([]byte, []int) {
	return file_bos_v1_constraints_proto_rawDescGZIP(), []int{6}
}

func (x *DurationConstraints) GetDefault() *Hours {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *DurationConstraints) GetMin() *Hours {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *DurationConstraints) GetMax() *Hours {
	if x != nil {
		return x.Max
	}
	return nil
}

type FrequencyConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default *Frequency `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Min     *Frequency `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	Max     *Frequency `protobuf:"bytes,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *FrequencyConstraints) Reset() {
	*x = FrequencyConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_constraints_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FrequencyConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrequencyConstraints) ProtoMessage() {}

func (x *FrequencyConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_constraints_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrequencyConstraints.ProtoReflect.Descriptor instead.
func (*FrequencyConstraints) Descriptor() ([]byte, []int) {
	return file_bos_v1_constraints_proto_rawDescGZIP(), []int{7}
}

func (x *FrequencyConstraints) GetDefault() *Frequency {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *FrequencyConstraints) GetMin() *Frequency {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *FrequencyConstraints) GetMax() *Frequency {
	if x != nil {
		return x.Max
	}
	return nil
}

type VoltageConstraints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Default *Voltage `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Min     *Voltage `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	Max     *Voltage `protobuf:"bytes,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *VoltageConstraints) Reset() {
	*x = VoltageConstraints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_constraints_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoltageConstraints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoltageConstraints) ProtoMessage() {}

func (x *VoltageConstraints) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_constraints_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoltageConstraints.ProtoReflect.Descriptor instead.
func (*VoltageConstraints) Descriptor() ([]byte, []int) {
	return file_bos_v1_constraints_proto_rawDescGZIP(), []int{8}
}

func (x *VoltageConstraints) GetDefault() *Voltage {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *VoltageConstraints) GetMin() *Voltage {
	if x != nil {
		return x.Min
	}
	return nil
}

func (x *VoltageConstraints) GetMax() *Voltage {
	if x != nil {
		return x.Max
	}
	return nil
}

var File_bos_v1_constraints_proto protoreflect.FileDescriptor

var file_bos_v1_constraints_proto_rawDesc = []byte{
	0x0a, 0x18, 0x62, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61,
	0x69, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x62, 0x72, 0x61, 0x69,
	0x69, 0x6e, 0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x12, 0x62, 0x6f, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x51,
	0x0a, 0x11, 0x55, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x61,
	0x78, 0x22, 0x51, 0x0a, 0x11, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6d,
	0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x03, 0x6d, 0x61, 0x78, 0x22, 0x95, 0x01, 0x0a, 0x10, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x2f, 0x0a, 0x07, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x72, 0x61,
	0x69, 0x69, 0x6e, 0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x77, 0x65,
	0x72, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x27, 0x0a, 0x03, 0x6d, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e,
	0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x03,
	0x6d, 0x69, 0x6e, 0x12, 0x27, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0xad, 0x01, 0x0a,
	0x13, 0x48, 0x61, 0x73, 0x68, 0x72, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61,
	0x69, 0x6e, 0x74, 0x73, 0x12, 0x36, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73, 0x2e,
	0x62, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x72, 0x61, 0x48, 0x61, 0x73, 0x68, 0x72,
	0x61, 0x74, 0x65, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x2e, 0x0a, 0x03,
	0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x72, 0x61, 0x69,
	0x69, 0x6e, 0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x72, 0x61, 0x48,
	0x61, 0x73, 0x68, 0x72, 0x61, 0x74, 0x65, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x2e, 0x0a, 0x03,
	0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x72, 0x61, 0x69,
	0x69, 0x6e, 0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x72, 0x61, 0x48,
	0x61, 0x73, 0x68, 0x72, 0x61, 0x74, 0x65, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0xad, 0x01, 0x0a,
	0x16, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x35, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x69,
	0x6e, 0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x2d,
	0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x72,
	0x61, 0x69, 0x69, 0x6e, 0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x6d,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x2d, 0x0a,
	0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x62, 0x72, 0x61,
	0x69, 0x69, 0x6e, 0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x6d, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x2d, 0x0a, 0x11,
	0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x22, 0x98, 0x01, 0x0a, 0x13,
	0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69,
	0x6e, 0x74, 0x73, 0x12, 0x2f, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73, 0x2e, 0x62,
	0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x07, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x12, 0x27, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x27, 0x0a,
	0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x72, 0x61,
	0x69, 0x69, 0x6e, 0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x75, 0x72,
	0x73, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0xa5, 0x01, 0x0a, 0x14, 0x46, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12,
	0x33, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x07, 0x64, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x03, 0x6d, 0x69,
	0x6e, 0x12, 0x2b, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x9d,
	0x01, 0x0a, 0x12, 0x56, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x31, 0x0a, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73,
	0x2e, 0x62, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x52,
	0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x29, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73, 0x2e,
	0x62, 0x6f, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x52, 0x03,
	0x6d, 0x69, 0x6e, 0x12, 0x29, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73, 0x2e, 0x62, 0x6f, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x56, 0x6f, 0x6c, 0x74, 0x61, 0x67, 0x65, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x42, 0x3d,
	0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x61,
	0x69, 0x69, 0x6e, 0x73, 0x2f, 0x62, 0x6f, 0x73, 0x2d, 0x70, 0x6c, 0x75, 0x73, 0x2d, 0x61, 0x70,
	0x69, 0x2f, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73, 0x2f, 0x62, 0x6f, 0x73, 0x2f, 0x76, 0x31,
	0x3b, 0x62, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bos_v1_constraints_proto_rawDescOnce sync.Once
	file_bos_v1_constraints_proto_rawDescData = file_bos_v1_constraints_proto_rawDesc
)

func file_bos_v1_constraints_proto_rawDescGZIP() []byte {
	file_bos_v1_constraints_proto_rawDescOnce.Do(func() {
		file_bos_v1_constraints_proto_rawDescData = protoimpl.X.CompressGZIP(file_bos_v1_constraints_proto_rawDescData)
	})
	return file_bos_v1_constraints_proto_rawDescData
}

var file_bos_v1_constraints_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bos_v1_constraints_proto_goTypes = []interface{}{
	(*UInt32Constraints)(nil),      // 0: braiins.bos.v1.UInt32Constraints
	(*DoubleConstraints)(nil),      // 1: braiins.bos.v1.DoubleConstraints
	(*PowerConstraints)(nil),       // 2: braiins.bos.v1.PowerConstraints
	(*HashrateConstraints)(nil),    // 3: braiins.bos.v1.HashrateConstraints
	(*TemperatureConstraints)(nil), // 4: braiins.bos.v1.TemperatureConstraints
	(*BooleanConstraint)(nil),      // 5: braiins.bos.v1.BooleanConstraint
	(*DurationConstraints)(nil),    // 6: braiins.bos.v1.DurationConstraints
	(*FrequencyConstraints)(nil),   // 7: braiins.bos.v1.FrequencyConstraints
	(*VoltageConstraints)(nil),     // 8: braiins.bos.v1.VoltageConstraints
	(*Power)(nil),                  // 9: braiins.bos.v1.Power
	(*TeraHashrate)(nil),           // 10: braiins.bos.v1.TeraHashrate
	(*Temperature)(nil),            // 11: braiins.bos.v1.Temperature
	(*Hours)(nil),                  // 12: braiins.bos.v1.Hours
	(*Frequency)(nil),              // 13: braiins.bos.v1.Frequency
	(*Voltage)(nil),                // 14: braiins.bos.v1.Voltage
}
var file_bos_v1_constraints_proto_depIdxs = []int32{
	9,  // 0: braiins.bos.v1.PowerConstraints.default:type_name -> braiins.bos.v1.Power
	9,  // 1: braiins.bos.v1.PowerConstraints.min:type_name -> braiins.bos.v1.Power
	9,  // 2: braiins.bos.v1.PowerConstraints.max:type_name -> braiins.bos.v1.Power
	10, // 3: braiins.bos.v1.HashrateConstraints.default:type_name -> braiins.bos.v1.TeraHashrate
	10, // 4: braiins.bos.v1.HashrateConstraints.min:type_name -> braiins.bos.v1.TeraHashrate
	10, // 5: braiins.bos.v1.HashrateConstraints.max:type_name -> braiins.bos.v1.TeraHashrate
	11, // 6: braiins.bos.v1.TemperatureConstraints.default:type_name -> braiins.bos.v1.Temperature
	11, // 7: braiins.bos.v1.TemperatureConstraints.min:type_name -> braiins.bos.v1.Temperature
	11, // 8: braiins.bos.v1.TemperatureConstraints.max:type_name -> braiins.bos.v1.Temperature
	12, // 9: braiins.bos.v1.DurationConstraints.default:type_name -> braiins.bos.v1.Hours
	12, // 10: braiins.bos.v1.DurationConstraints.min:type_name -> braiins.bos.v1.Hours
	12, // 11: braiins.bos.v1.DurationConstraints.max:type_name -> braiins.bos.v1.Hours
	13, // 12: braiins.bos.v1.FrequencyConstraints.default:type_name -> braiins.bos.v1.Frequency
	13, // 13: braiins.bos.v1.FrequencyConstraints.min:type_name -> braiins.bos.v1.Frequency
	13, // 14: braiins.bos.v1.FrequencyConstraints.max:type_name -> braiins.bos.v1.Frequency
	14, // 15: braiins.bos.v1.VoltageConstraints.default:type_name -> braiins.bos.v1.Voltage
	14, // 16: braiins.bos.v1.VoltageConstraints.min:type_name -> braiins.bos.v1.Voltage
	14, // 17: braiins.bos.v1.VoltageConstraints.max:type_name -> braiins.bos.v1.Voltage
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_bos_v1_constraints_proto_init() }
func file_bos_v1_constraints_proto_init() {
	if File_bos_v1_constraints_proto != nil {
		return
	}
	file_bos_v1_units_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bos_v1_constraints_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UInt32Constraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_constraints_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_constraints_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PowerConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_constraints_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashrateConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_constraints_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TemperatureConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_constraints_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BooleanConstraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_constraints_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DurationConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_constraints_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FrequencyConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_constraints_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoltageConstraints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bos_v1_constraints_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bos_v1_constraints_proto_goTypes,
		DependencyIndexes: file_bos_v1_constraints_proto_depIdxs,
		MessageInfos:      file_bos_v1_constraints_proto_msgTypes,
	}.Build()
	File_bos_v1_constraints_proto = out.File
	file_bos_v1_constraints_proto_rawDesc = nil
	file_bos_v1_constraints_proto_goTypes = nil
	file_bos_v1_constraints_proto_depIdxs = nil
}
