// Copyright (C) 2023  Braiins Systems s.r.o.
//
// This file is part of Braiins Open-Source Initiative (BOSI).
//
// BOSI is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// Please, keep in mind that we may also license BOSI or any part thereof
// under a proprietary license. For more information on the terms and conditions
// of such proprietary license or if you have any other questions, please
// contact us at opensource@braiins.com.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: bos/v1/units.proto

package bos_proto_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MegaHashrate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MegahashPerSecond float64 `protobuf:"fixed64,1,opt,name=megahash_per_second,json=megahashPerSecond,proto3" json:"megahash_per_second,omitempty"`
}

func (x *MegaHashrate) Reset() {
	*x = MegaHashrate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_units_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MegaHashrate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MegaHashrate) ProtoMessage() {}

func (x *MegaHashrate) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_units_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MegaHashrate.ProtoReflect.Descriptor instead.
func (*MegaHashrate) Descriptor() ([]byte, []int) {
	return file_bos_v1_units_proto_rawDescGZIP(), []int{0}
}

func (x *MegaHashrate) GetMegahashPerSecond() float64 {
	if x != nil {
		return x.MegahashPerSecond
	}
	return 0
}

type GigaHashrate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GigahashPerSecond float64 `protobuf:"fixed64,1,opt,name=gigahash_per_second,json=gigahashPerSecond,proto3" json:"gigahash_per_second,omitempty"`
}

func (x *GigaHashrate) Reset() {
	*x = GigaHashrate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_units_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GigaHashrate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GigaHashrate) ProtoMessage() {}

func (x *GigaHashrate) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_units_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GigaHashrate.ProtoReflect.Descriptor instead.
func (*GigaHashrate) Descriptor() ([]byte, []int) {
	return file_bos_v1_units_proto_rawDescGZIP(), []int{1}
}

func (x *GigaHashrate) GetGigahashPerSecond() float64 {
	if x != nil {
		return x.GigahashPerSecond
	}
	return 0
}

type TeraHashrate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TerahashPerSecond float64 `protobuf:"fixed64,1,opt,name=terahash_per_second,json=terahashPerSecond,proto3" json:"terahash_per_second,omitempty"`
}

func (x *TeraHashrate) Reset() {
	*x = TeraHashrate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_units_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TeraHashrate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeraHashrate) ProtoMessage() {}

func (x *TeraHashrate) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_units_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeraHashrate.ProtoReflect.Descriptor instead.
func (*TeraHashrate) Descriptor() ([]byte, []int) {
	return file_bos_v1_units_proto_rawDescGZIP(), []int{2}
}

func (x *TeraHashrate) GetTerahashPerSecond() float64 {
	if x != nil {
		return x.TerahashPerSecond
	}
	return 0
}

type Frequency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hertz float64 `protobuf:"fixed64,1,opt,name=hertz,proto3" json:"hertz,omitempty"`
}

func (x *Frequency) Reset() {
	*x = Frequency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_units_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Frequency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frequency) ProtoMessage() {}

func (x *Frequency) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_units_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frequency.ProtoReflect.Descriptor instead.
func (*Frequency) Descriptor() ([]byte, []int) {
	return file_bos_v1_units_proto_rawDescGZIP(), []int{3}
}

func (x *Frequency) GetHertz() float64 {
	if x != nil {
		return x.Hertz
	}
	return 0
}

type Voltage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Volt float64 `protobuf:"fixed64,1,opt,name=volt,proto3" json:"volt,omitempty"`
}

func (x *Voltage) Reset() {
	*x = Voltage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_units_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Voltage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Voltage) ProtoMessage() {}

func (x *Voltage) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_units_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Voltage.ProtoReflect.Descriptor instead.
func (*Voltage) Descriptor() ([]byte, []int) {
	return file_bos_v1_units_proto_rawDescGZIP(), []int{4}
}

func (x *Voltage) GetVolt() float64 {
	if x != nil {
		return x.Volt
	}
	return 0
}

type Power struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Watt uint64 `protobuf:"varint,1,opt,name=watt,proto3" json:"watt,omitempty"`
}

func (x *Power) Reset() {
	*x = Power{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_units_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Power) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Power) ProtoMessage() {}

func (x *Power) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_units_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Power.ProtoReflect.Descriptor instead.
func (*Power) Descriptor() ([]byte, []int) {
	return file_bos_v1_units_proto_rawDescGZIP(), []int{5}
}

func (x *Power) GetWatt() uint64 {
	if x != nil {
		return x.Watt
	}
	return 0
}

type PowerEfficiency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JoulePerTerahash float64 `protobuf:"fixed64,1,opt,name=joule_per_terahash,json=joulePerTerahash,proto3" json:"joule_per_terahash,omitempty"`
}

func (x *PowerEfficiency) Reset() {
	*x = PowerEfficiency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_units_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PowerEfficiency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowerEfficiency) ProtoMessage() {}

func (x *PowerEfficiency) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_units_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowerEfficiency.ProtoReflect.Descriptor instead.
func (*PowerEfficiency) Descriptor() ([]byte, []int) {
	return file_bos_v1_units_proto_rawDescGZIP(), []int{6}
}

func (x *PowerEfficiency) GetJoulePerTerahash() float64 {
	if x != nil {
		return x.JoulePerTerahash
	}
	return 0
}

type Temperature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DegreeC float64 `protobuf:"fixed64,1,opt,name=degree_c,json=degreeC,proto3" json:"degree_c,omitempty"`
}

func (x *Temperature) Reset() {
	*x = Temperature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_units_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Temperature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Temperature) ProtoMessage() {}

func (x *Temperature) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_units_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Temperature.ProtoReflect.Descriptor instead.
func (*Temperature) Descriptor() ([]byte, []int) {
	return file_bos_v1_units_proto_rawDescGZIP(), []int{7}
}

func (x *Temperature) GetDegreeC() float64 {
	if x != nil {
		return x.DegreeC
	}
	return 0
}

// Structure representing Basis Points
type BasesPoints struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A basis point is one hundredth of 1 percentage point.
	// For example: 1bps = 0.01%, 250bps = 2.5%
	Bsp uint32 `protobuf:"varint,1,opt,name=bsp,proto3" json:"bsp,omitempty"`
}

func (x *BasesPoints) Reset() {
	*x = BasesPoints{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_units_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BasesPoints) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasesPoints) ProtoMessage() {}

func (x *BasesPoints) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_units_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasesPoints.ProtoReflect.Descriptor instead.
func (*BasesPoints) Descriptor() ([]byte, []int) {
	return file_bos_v1_units_proto_rawDescGZIP(), []int{8}
}

func (x *BasesPoints) GetBsp() uint32 {
	if x != nil {
		return x.Bsp
	}
	return 0
}

type Hours struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hours uint32 `protobuf:"varint,1,opt,name=hours,proto3" json:"hours,omitempty"`
}

func (x *Hours) Reset() {
	*x = Hours{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bos_v1_units_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hours) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hours) ProtoMessage() {}

func (x *Hours) ProtoReflect() protoreflect.Message {
	mi := &file_bos_v1_units_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hours.ProtoReflect.Descriptor instead.
func (*Hours) Descriptor() ([]byte, []int) {
	return file_bos_v1_units_proto_rawDescGZIP(), []int{9}
}

func (x *Hours) GetHours() uint32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

var File_bos_v1_units_proto protoreflect.FileDescriptor

var file_bos_v1_units_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73, 0x2e, 0x62, 0x6f,
	0x73, 0x2e, 0x76, 0x31, 0x22, 0x3e, 0x0a, 0x0c, 0x4d, 0x65, 0x67, 0x61, 0x48, 0x61, 0x73, 0x68,
	0x72, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x6d, 0x65, 0x67, 0x61, 0x68, 0x61, 0x73, 0x68,
	0x5f, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x11, 0x6d, 0x65, 0x67, 0x61, 0x68, 0x61, 0x73, 0x68, 0x50, 0x65, 0x72, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x22, 0x3e, 0x0a, 0x0c, 0x47, 0x69, 0x67, 0x61, 0x48, 0x61, 0x73, 0x68,
	0x72, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x67, 0x69, 0x67, 0x61, 0x68, 0x61, 0x73, 0x68,
	0x5f, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x11, 0x67, 0x69, 0x67, 0x61, 0x68, 0x61, 0x73, 0x68, 0x50, 0x65, 0x72, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x22, 0x3e, 0x0a, 0x0c, 0x54, 0x65, 0x72, 0x61, 0x48, 0x61, 0x73, 0x68,
	0x72, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x13, 0x74, 0x65, 0x72, 0x61, 0x68, 0x61, 0x73, 0x68,
	0x5f, 0x70, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x11, 0x74, 0x65, 0x72, 0x61, 0x68, 0x61, 0x73, 0x68, 0x50, 0x65, 0x72, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x22, 0x21, 0x0a, 0x09, 0x46, 0x72, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x65, 0x72, 0x74, 0x7a, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x05, 0x68, 0x65, 0x72, 0x74, 0x7a, 0x22, 0x1d, 0x0a, 0x07, 0x56, 0x6f, 0x6c, 0x74, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x6f, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x76, 0x6f, 0x6c, 0x74, 0x22, 0x1b, 0x0a, 0x05, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x12,
	0x12, 0x0a, 0x04, 0x77, 0x61, 0x74, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x77,
	0x61, 0x74, 0x74, 0x22, 0x3f, 0x0a, 0x0f, 0x50, 0x6f, 0x77, 0x65, 0x72, 0x45, 0x66, 0x66, 0x69,
	0x63, 0x69, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x2c, 0x0a, 0x12, 0x6a, 0x6f, 0x75, 0x6c, 0x65, 0x5f,
	0x70, 0x65, 0x72, 0x5f, 0x74, 0x65, 0x72, 0x61, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x10, 0x6a, 0x6f, 0x75, 0x6c, 0x65, 0x50, 0x65, 0x72, 0x54, 0x65, 0x72, 0x61,
	0x68, 0x61, 0x73, 0x68, 0x22, 0x28, 0x0a, 0x0b, 0x54, 0x65, 0x6d, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x5f, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65, 0x43, 0x22, 0x1f,
	0x0a, 0x0b, 0x42, 0x61, 0x73, 0x65, 0x73, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x10, 0x0a,
	0x03, 0x62, 0x73, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x62, 0x73, 0x70, 0x22,
	0x1d, 0x0a, 0x05, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x75, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x42, 0x3d,
	0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x61,
	0x69, 0x69, 0x6e, 0x73, 0x2f, 0x62, 0x6f, 0x73, 0x2d, 0x70, 0x6c, 0x75, 0x73, 0x2d, 0x61, 0x70,
	0x69, 0x2f, 0x62, 0x72, 0x61, 0x69, 0x69, 0x6e, 0x73, 0x2f, 0x62, 0x6f, 0x73, 0x2f, 0x76, 0x31,
	0x3b, 0x62, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bos_v1_units_proto_rawDescOnce sync.Once
	file_bos_v1_units_proto_rawDescData = file_bos_v1_units_proto_rawDesc
)

func file_bos_v1_units_proto_rawDescGZIP() []byte {
	file_bos_v1_units_proto_rawDescOnce.Do(func() {
		file_bos_v1_units_proto_rawDescData = protoimpl.X.CompressGZIP(file_bos_v1_units_proto_rawDescData)
	})
	return file_bos_v1_units_proto_rawDescData
}

var file_bos_v1_units_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_bos_v1_units_proto_goTypes = []interface{}{
	(*MegaHashrate)(nil),    // 0: braiins.bos.v1.MegaHashrate
	(*GigaHashrate)(nil),    // 1: braiins.bos.v1.GigaHashrate
	(*TeraHashrate)(nil),    // 2: braiins.bos.v1.TeraHashrate
	(*Frequency)(nil),       // 3: braiins.bos.v1.Frequency
	(*Voltage)(nil),         // 4: braiins.bos.v1.Voltage
	(*Power)(nil),           // 5: braiins.bos.v1.Power
	(*PowerEfficiency)(nil), // 6: braiins.bos.v1.PowerEfficiency
	(*Temperature)(nil),     // 7: braiins.bos.v1.Temperature
	(*BasesPoints)(nil),     // 8: braiins.bos.v1.BasesPoints
	(*Hours)(nil),           // 9: braiins.bos.v1.Hours
}
var file_bos_v1_units_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bos_v1_units_proto_init() }
func file_bos_v1_units_proto_init() {
	if File_bos_v1_units_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bos_v1_units_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MegaHashrate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_units_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GigaHashrate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_units_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TeraHashrate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_units_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Frequency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_units_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Voltage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_units_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Power); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_units_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PowerEfficiency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_units_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Temperature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_units_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BasesPoints); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bos_v1_units_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hours); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bos_v1_units_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bos_v1_units_proto_goTypes,
		DependencyIndexes: file_bos_v1_units_proto_depIdxs,
		MessageInfos:      file_bos_v1_units_proto_msgTypes,
	}.Build()
	File_bos_v1_units_proto = out.File
	file_bos_v1_units_proto_rawDesc = nil
	file_bos_v1_units_proto_goTypes = nil
	file_bos_v1_units_proto_depIdxs = nil
}
